language: clojure
lein: lein2
jdk:
  - oraclejdk7
  - oraclejdk8
services:
  - riak
cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2
sudo: false
install:
  - wget https://b25518159d104e8997f8-d5f47ab458856b6ee0c2780ddf5e291c.ssl.cf5.rackcdn.com/libsodium-1.0.2_amd64.deb
  - mkdir local
  - dpkg-deb --vextract libsodium*.deb local
  - lein deps :tree
env:
  - LD_LIBRARY_PATH=local/usr/lib
script:
  - lein test :all
  - lein lint || true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/302d39a4035a26199602
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
